### ISSUE TITLE
iOS app intermittent 502 errors

### ISSUE THREAD

**Issue by sgwoods** [metabolist/metatext#115]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**(please complete the following information):**
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 14.4.1]
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by prplecake** [comment]
Somehow I doubt you could have provided less information. Well done.

**Comment by sgwoods** [comment]
Fair point.  If there is something specific, ask.  I rather assumed an error like this was rather common if I am experiencing it  at the frequency I am and assumed it was load related on the server side given current circumstances and the precarious architecture of the federated mastodon universe and that my bug would disappear into the massive volume of issues occurring with trying to handle slow servers, failed modalities such as photo processing/posting, hours-wait for refreshes between servers for posting and what-not. Apologies.

Here are some screenshots which are the best I am able to do at seeing if I can recreate and context capture. Happy to take more if something is needed.
https://www.icloud.com/photos/#02cELHfIWfbfjMqmdG495P-8A

IOS on Iphone 12 up to date- 16.1.  Firmware 3.07.00
Issue has occurred on wifi and on LTE
App is up to date - 

As an aside.
* If the app had a submit feedback button that captured the state and allowed me to upload it I would use it.  same for the app store.

1. Get "Request timed out" popup fairly regularly (502 at others) but  unpredictably while viewing the app.  In home tab for sure, not sure about others - will try to make a mental note of it.  Perhaps after coming back from other apps or not - hard to tell but thats my bet.  I could send a screenshot but it has no other context.

2.  I tried for 5 minutes switching tabs on bottom, switching home/local/fed at top, scrolling, restarting app and relaunching and trying again - without success at recreating 

3. The problem has happened perhaps 10x in the last two days of my usage - the vast majority of my usage will be early morning EDT and mid-evening EDT.

When it recurs I will resubmit additional context. If you want me to try anything else, or submit, just respond and ask I will attempt to help more specifically.  

S

**Comment by nighthawk** [comment]
502 errors mean that there was a server-side issue, e.g., the instance is overloaded, down for maintenance, or is experiencing some other issues. A common occurrence lately due to the quick uptake of new users.

Not much the app can do to avoid it, but it would be good if it provided an indication that there are issues with the instance. The official app shows a big red bubble in the navigation bar saying "Offline". Might be worth adding to Metatext if it doesn't yet do something like that.
