### ISSUE TITLE
Parma is missing or the value is empty

### ISSUE THREAD

**Issue by BOhUiginn** [metabolist/metatext#122]
When I enter the explore tab an error immediately pops up. This error will occasionally pop up while typing a search. 

**To Reproduce**
1. Go to 'Explore tab'
2. Error will pop up saying: "param is missing or the value is empty: q
Did you mean? q
action controller limit" with only an option for "OK".

There should be no error pop up when entering the explore tab. 
![image](https://user-images.githubusercontent.com/2617501/200895665-37ad4114-3e55-41d8-9b11-5492e3f49bed.png)

 - Device: iPhone 12 Pro
 - OS: iOS 16.0.3 (20A392)
 - App Version: 1.5.1 (2)

**Comment by jzzocc** [comment]
Fixed in v1.5.2
