### ISSUE TITLE
Multiple taps required to favorite or boost.

### ISSUE THREAD

**Issue by Maddest-Max** [metabolist/metatext#124]
**Describe the bug**
Favoriting or boosting a toot takes multiple taps on the icon to make it work. 

**To Reproduce**
1. Go to any toot. 
2. Click on the star or the boost icon. 
3. Have it not function until tapped multiple times. 

**Expected behavior**
One tap should work. 

 - Device: iPhone 11
 - OS: iOS v6.1
 - App Version v1.5.1

**Comment by prplecake** [comment]
Might I suggest checking your app settings?

![image](https://user-images.githubusercontent.com/83595468/200954944-87da2350-152b-4ec9-b49b-bfeb9430c195.jpeg)

**Comment by Maddest-Max** [comment]
You're absolutely correct. I wonder if those got automatically changed in the last update. I've been using the app for over a year and never had the issue. Thanks for pointing it out. I'll mark the issue resolved.
