### ISSUE TITLE
Support toggling light/dark mode in app

### ISSUE THREAD

**Issue by kiendang** [metabolist/metatext#126]
**Is your feature request related to a problem? Please describe.**
Currently the only way to toggle the app light/dark mode is to toggle light/dark mode in the phone settings. There's no way to do this in app as far as I know.

Thanks for developing this app btw, great UI/UX and looks.

**Describe the solution you'd like**
Would be great if light/dark mode can be toggled manually inside the app's preferences.

**Describe alternatives you've considered**

**Additional context**

**Comment by vollkorntomate** [comment]
Possible duplicate of #73
