### ISSUE TITLE
adjust right-side margin

### ISSUE THREAD

**Issue by bourgwick** [metabolist/metatext#133]
**Is your feature request related to a problem? Please describe.**

I scroll the timeline with my right thumb and very, very often accidentally engage the 3 dots to block/mute users.

**Describe the solution you'd like**

Is there a way to widen the right margin or move the 3 dots inward slightly?

**Describe alternatives you've considered**

Using another app (but I like MetaText a lot otherwise).

**Additional context**

**Comment by prplecake** [comment]
can't repro

**Comment by bourgwick** [comment]
I keep activating them accidentally as such while trying to read the timeline.

![dots1](https://user-images.githubusercontent.com/117941608/201195203-9751385a-ed44-4cc5-b4cd-8e3958761a2d.jpeg)
![dots2](https://user-images.githubusercontent.com/117941608/201195220-0ba0b987-1090-4dac-8a90-1bc38d07776d.jpeg)

**Comment by jzzocc** [comment]
Noted for a possible future redesign
