### ISSUE TITLE
New Notifications Available Indicator

### ISSUE THREAD

**Issue by RobATX** [metabolist/metatext#137]
**Is your feature request related to a problem? Please describe.**
The Notifications bell icon at the bottom of the app does not "light up" or show an indication of new notifications. Is this something that that can be added? 

**Describe the solution you'd like**
A visual cue in the Notificarions icon that indicates new messages. 

**Describe alternatives you've considered**
Have to always check for new notifications. 

**Additional context**
N/A

**Comment by Beercow** [comment]
Same issue here.

**Comment by jzzocc** [comment]
See #51

**Comment by runevision** [comment]
This feature request is not the same as #51. #51 is about a badge on the app icon. The feature request here is about a dot on the bell icon inside the app. Mainstream social apps like Twitter and Facebook have both of these things, so you can see presence of unread notifications no matter of the app is open or not.

If #51 is viewed as also covering a dot on the bell icon inside the app, that should be made more clear in #51. It currently seems to be about a badge on the app icon only.
