### ISSUE TITLE
Toot with link and CW is not hiding link preview

### ISSUE THREAD

**Issue by patrick330602** [metabolist/metatext#139]
**Describe the bug**

Toot with link and CW (content warning) is not hiding link preview, still visible under Show more.

**To Reproduce**
1. Add a new toot with CW with some text and link at the button
2. Go to home page and view , text and link are properly hidden but preview is still visible

**Expected behavior**
link preview is hidden until I pressed Show More

**Screenshots**
![IMG_5812](https://user-images.githubusercontent.com/15316889/201254360-4f58a8f6-7dff-4a29-abd0-18b5383ede94.PNG)
**(please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.1.1
 - App Version 1.5.2(2)

**Additional context**

**Comment by jzzocc** [comment]
See #58
