### ISSUE TITLE
Emoji picker doesn't appear when replying

### ISSUE THREAD

**Issue by eldang** [metabolist/metatext#14]
**Describe the bug**
When I reply to a toot, the smiley-face emoji picker control seems to be inert.  When I write a toot that is not a reply, touching the same control gives me a very nice emoji picker that includes my instance's custom emoji (thank you for that feature!).

**To Reproduce**
1. Reply to a toot.
2. Touch the app's built-in emoji picker control.
3. Nothing happens.
4. Switch to iOS's default emoji keyboard.
5. That still works, but doesn't have the custom emoji in it.

**Expected behavior**
I would expect the app's much nicer emoji picker to show up, as it does when I'm not replying to a toot.

**(please complete the following information):**
 - Device: iPhone SE (2021 version)
 - OS: iOS 14.4.1
 - App Version: 1.0.2 (2)

**Additional context**
I think this was also happening in v1.0.1, but I hadn't had the time to test it well enough to write up a useful bug report until today.

**Comment by jzzocc** [comment]
I can reproduce this, but only on posts with content warnings, and believe I know what the issue is. Can you confirm that it works when replying to a post without a content warning?

In the meantime, a workaround is to select the content warning text field, then select the main text field again.

**Comment by eldang** [comment]
Ah!  You're right, I can also only repro this when the toot I'm replying to had a CW.
