### ISSUE TITLE
App language selector

### ISSUE THREAD

**Issue by queerterpreter** [metabolist/metatext#150]
While it’s great that the app is available in different languages, the translations (at least into Spanish) aren’t… great. For example, when you look at someone’s profile, instead of saying “(they) joined N (date),” it says “(you) joined N (people).”

The app looks great and I really want to use it, but it seems like it’s determining display language based on device language, and “change your phone to English” won’t work for me.

Can a language selector be added to the app settings, please? (And if it’s already there, can someone show me where? I’ve looked everywhere.)

**Comment by f2k1de** [comment]
On iOS you can select for each App a different language in the Settings App. No need to set the whole phone to English

**Comment by jzzocc** [comment]
Open the iOS Settings app, scroll down to Metatext, and there will be an option to set the language just for the app.
