### ISSUE TITLE
Feature: long-tap on hashtag to show options

### ISSUE THREAD

**Issue by yuki-93** [metabolist/metatext#151]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
When tapping on a hashtag in a toot, show options menu. I would like to have options for muting/silencing the selected hashtag. Maybe also look for the hashtag in the search. 

**Additional context**
Some hashtags might be difficult to spell and the mute menu is several tapps away.

**Comment by jzzocc** [comment]
See #146
