### ISSUE TITLE
Add German Informal (du)

### ISSUE THREAD

**Issue by f2k1de** [metabolist/metatext#152]
**Is your feature request related to a problem? Please describe.**
The App has currently just one setting for german, the formal form (Sie). It would nice to have also the informal (Du) form because many users are hanging out in the Fediverse with their family and friends. 

**Describe the solution you'd like**
Implement 2 german variants and let the user choose which one they want to be addressed.

**Comment by jzzocc** [comment]
Informal German is not a locale that is supported on iOS

**Comment by f2k1de** [comment]
Then maybe switch the whole german translation to du, like almost all other social media apps do?
