### ISSUE TITLE
Print the user name always

### ISSUE THREAD

**Issue by f2k1de** [metabolist/metatext#153]
**Is your feature request related to a problem? Please describe.**
I have different accounts on different instances. Currently I dont know which Account i am using because the profile picture is the only indicator to distinguish them. It would be nice if I could see always on top of the timeline from which account / instance this is the timeline I am looking at. 

**Describe the solution you'd like**
Display the username and instance on top of the timeline view and when composing a post.

**Comment by jzzocc** [comment]
Noted for future redesigns
