### ISSUE TITLE
Sync account list & settings across devices

### ISSUE THREAD

**Issue by dschuetz** [metabolist/metatext#183]
I'm setting up Metatext on multiple devices (home and work systems, iPhone, iPad) and find myself repeatedly re-entering account information. I'm trying different servers for different community focuses, and also have a couple specific servers I just want to try and browse.

Could all this information sync across devices (probably via iCloud -- preferably not iCloud Drive since work blocks that :) ). 

If security of authentication tokens is a concern, it seems reasonable to sync everything but the tokens, and we'd just have to re-authenticate to servers the first time you actually switch to an account on a different device.

**Comment by jzzocc** [comment]
Unfortunately interaction with a syncing service involving a 3rd-party API is out of scope for the project at this time
