### ISSUE TITLE
Thank you! (and make your donation options more visible maybe)

### ISSUE THREAD

**Issue by larsimmisch** [metabolist/metatext#190]
This is not actually a feature request, it's a Thank You! This is a great looking app and I like it a lot better then the official one.

Kudos to you.

It's just that I think that making donations a bit easier might be a good idea. If https://opencollective.com/metabolist is the right place, maybe make it accessible from the app?

**Comment by jzzocc** [comment]
Prefer to keep it subtle for now, but thanks for your enthusiasm!
