### ISSUE TITLE
Account Settings & Edit Profile opens wrong link on servers with different local and web domain

### ISSUE THREAD

**Issue by NoaHimesaka1873** [metabolist/metatext#195]
**Describe the bug**
Account Settings & Edit Profile opens wrong link on servers with different local and web domain

**To Reproduce**
1. Touch profile picture on the top left
2. Click on 'Account Settings' or 'Edit Profile'

**Expected behavior**
Opens proper link with web domain

**Screenshots**
https://user-images.githubusercontent.com/39993457/202700375-adf2814e-3be4-4ee4-b507-6c144811741f.MOV

**(please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.2 DB
 - App Version 1.6.0

**Additional context**
Discovered by @Mafia_NO8@funami.tech on Mastodon.

**Comment by jaytay79** [comment]
FYI this has also been reported in #189
