### ISSUE TITLE
Add an option to display favorites as likes

### ISSUE THREAD

**Issue by iamdaniele** [metabolist/metatext#206]
**Is your feature request related to a problem? Please describe.**
Mastodon uses the "favorite" primitive to indicate that a user liked a post. This verb is often associated with the action of liking a post, something most users associated to "hearting" on more incumbent platforms. This creates a few problems:
- People who approach Mastodon for the first time may not immediately understand what a favorite is.
- Using favorites as a verb, and a star as its matching iconography created a steeper-than-needed learning curve for people who are migrating from other services or clients, as they may be more familiar with the like/heart design construct.
- People who are familiar with bookmarks on other platforms may be confused by the semantic proximity of "favorites" and "bookmarks".

**Describe the solution you'd like**
Add the ability to display favorites as likes. This should be implemented as a toggle (disabled by default), so the user can switch between favorites/stars and likes/hearts.

When the user chooses to display favorites as likes, the following should happen:
- Favorite actions (including notifications) will be displayed as likes
- Stars are replaced by hearts in StatusView and NotificationView
- The string "Favorites" and its noun/verb variations are replaces by "Likes" and its variation
- Favoriting a post should display a cute heartbeat animation, as opposed as a rotating star.

**Describe alternatives you've considered**
No alternative was considered.

**Comment by jzzocc** [comment]
I do very much appreciate all the thought put into this, but in the near term I think the app is going to be consistent with Mastodon's web idioms for this
