### ISSUE TITLE
Slow when loading more data from server

### ISSUE THREAD

**Issue by bitboxer** [metabolist/metatext#236]
**Describe the bug**

Somehow the app is lagging a lot every time i have the feeling it is contacting the server. At start, when i switch back to the app, when I click any of the interactions that result in a server call. 

It basically feels like the app is doing the calls in the UI thread and blocking the swift rendering engine. 

**To Reproduce**
1. Click on anything that needs a server get
2. See the ui blocking

**Expected behavior**
 Snappy app

**Comment by codebykat** [comment]
Happens to me too. Scrolling gets jerky / feels kinda unresponsive before the new posts alert shows. Also "Load More" has a delay between finishing to load and loading in the new posts.

Edited: My experience at least is a duplicate of https://github.com/metabolist/metatext/issues/221

**Comment by bitboxer** [comment]
Yeah, but it is more than just the new posts are loaded. It feels more like every interaction that has to get data from a server.

**Comment by alexbbrown** [comment]
This feels like #221

**Comment by bitboxer** [comment]
The latest release fixed it for me. Thanks 🥰🥰🥰
