### ISSUE TITLE
Load More arrows and gaps in the timeline are a pain

### ISSUE THREAD

**Issue by codebykat** [metabolist/metatext#237]
**Describe the bug**
1. The Load More arrows constantly trip me up.
2. I don't understand why they are there to begin with.

**To Reproduce**
Several times per day, the following happens:
1. I am scrolling through my timeline from oldest post to newer posts
3. The Load More arrows scroll into view
4. I scroll "incorrectly" (either because I scrolled too far and want to move the Load More bar back toward the top of my screen, or because I lifted my finger off it the wrong way when I finished scrolling)
5. The horrible little arrows smugly twist around to point downwards instead of upwards
6. If I don't notice this quickly enough to avoid tapping them, the posts "fill in" in the wrong direction, and I have to scroll backwards through my timeline looking for the last post I saw.

**Expected behavior**
1. I expect my entire timeline to just be there, I don't understand why I have to click this bar in the first place to load in all the posts. If nothing else it should be at the very top, there shouldn't be a "gap" of missing posts but older and newer ones are loaded. Just load them from oldest to newest and let me scroll to the top and pull to refresh if I want to skip to the present moment.
2. The arrows should have more of a delay before reversing direction when I scroll in a different direction. The number of times they have turned themselves around AS I TAP LOAD MORE! Or maybe don't flip them around unless I have scrolled them the way to the top or bottom of the screen.

**(please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 15.7
 - App Version 1.7.0

**Comment by jzzocc** [comment]
The gaps are there because the app only loads a limited amount of posts at a time, and it's my understanding that most users expect them to be there to understand where they are in their timeline chronologically. I agree the UI for directional loading needs to be redesigned at some point in the future

**Comment by codebykat** [comment]
> The gaps are there because the app only loads a limited amount of posts at a time, and it's my understanding that most users expect them to be there to understand where they are in their timeline chronologically.

My argument would be that if the app is loading a limited amount of posts at a time, they should all load oldest-to-newest OR newest-to-oldest but not some of each. So essentially if you're scrolling back, you get to the "end" (oldest post loaded) and say "Load More"; if you're scrolling forward, you get to the "end" (newest post that's been loaded) and say "Load More" to load the next chunk. Similar to pagination on websites; I expect a website with a bunch of articles to show me either the first or last group of those articles, not the first five and last five on the same page.

I might not be explaining this well; what I find confusing is not the communication of the gap, but that the app is loading X newest posts and X oldest posts at the same time, necessitating a gap in the first place.

That being said I get that it's a complex UI and not the biggest priority. Also saw your post saying you're looking for a new maintainer - thanks for all your work on this app, I appreciate it! It's been the only one I found usable to dip my toes into Mastodon. Take care of yourself.
