### ISSUE TITLE
Support for language tags

### ISSUE THREAD

**Issue by avrhmt** [metabolist/metatext#244]
**Is your feature request related to a problem? Please describe.**
Mastodon has the ability to tag posts by their language. This is applicable for when users filter the posts they see on their timeline based on the post’s language.
Currently this feature is not supported by Metatext, and as result all posts are tagged with the user’s default post language with no way to change that for a specific post.

**Describe the solution you'd like**
The ability to choose a post’s language at the time of composition

**Additional context**
A screenshot of language picker option on Mastodon web client 
![A1AF90B0-01C4-467C-81F9-88E5C1A9F097](https://user-images.githubusercontent.com/65495000/203967449-1b571d6a-4f7f-4927-9ffd-3f7918675918.jpeg)

**Comment by edraac** [comment]
Duplicate of #75 (I’d love to have this feature though! It’s currently the only reason I’m still using the web app).

**Comment by avrhmt** [comment]
@edraac Thanks. I must have missed that when searching for it.

**Comment by avrhmt** [comment]
Closing as duplicate
