### ISSUE TITLE
Show trending statuses AKA "Explore Posts"

### ISSUE THREAD

**Issue by patrickhoefler** [metabolist/metatext#255]
The Mastodon Web UI features a page to explore trending posts (e.g. the [explore posts page for mastodon.online](https://mastodon.social/explore)).

It would be great if this view were also available in Metatext.

The [API for the trending statuses](https://docs.joinmastodon.org/methods/trends/#statuses) is available since v3.5.0 at `/api/v1/trends/statuses` (e.g. the [API endpoint for the page above from mastodon.online](https://mastodon.social/api/v1/trends/statuses)).

**Comment by avrhmt** [comment]
This request has already been mentioned in issue #210

**Comment by patrickhoefler** [comment]
Sorry, didn't see that. Please feel free to delete this issue.
