### ISSUE TITLE
Badge notifications (red circle) not working in Metatext on iOS

### ISSUE THREAD

**Issue by simondueckert** [metabolist/metatext#260]
**Describe the bug**
Notification does not work on iOS App ([Badge Number](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/))

**To Reproduce**
1. Go to 'Setting/Notifications' in the app and swith everything 'On'
2. Go to 'Settings/Notifications/Metatext' in iOS and switch badge notification on ("Kennzeichen" in German)

**Expected behavior**
The app shows badge numbers on the top right corner of the app icon.

**Screenshots**
NA

**(please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.1.1
 - App Version 1.7.0

**Additional context**
NA

**Comment by jzzocc** [comment]
See #51
