### ISSUE TITLE
Link navigating to toot instead of browser

### ISSUE THREAD

**Issue by 5teveroy** [metabolist/metatext#27]
**Steps to reproduce**
1. Navigate to [this toot](https://fosstodon.org/@PINE64/105971145040590259) in Metatext 1.1.
2. Observe that the entire text past the hash tag incorrectly appears as a link.
3. Tap the pine64.com link at the bottom of the toot.

**Expected result**: The toot opens in the browser as configured in settings.

**Actual result**: The toot pushes another view controller displaying itself.

**Comment by 5teveroy** [comment]
![C924C155-ABBD-4659-ABC8-4B5E9C6B10B9](https://user-images.githubusercontent.com/6139217/112789028-1f1db980-902a-11eb-860a-e84837c32507.png)

**Comment by MarcoZehe** [comment]
I can confirm this, sort of. For me, it doesn't reopen the toot, but activates the hash tag for that notebook. And I then run into "Too many requests" errors.
I then looked at the pine64-Profile via Pinafore on the wweb, and noticed that the accessible label for the toot didn't come through in the "pinned toots" section, but was read fine in the "normal toots" section below. Also, I could open the toot in Pinafore's toot view fine, the hashtag and actual web address were clearly separated.

So it does seem to have something to do when the toot is delivered via the pinned toots batch.

**Comment by jzzocc** [comment]
This will be fixed in v1.1.1
