### ISSUE TITLE
"Add/remove from lists" is displayed for users who cannot operate the list

### ISSUE THREAD

**Issue by noellabo** [metabolist/metatext#3]
All users see "Add / remove from lists", but it doesn't work for users who aren't following. A condition to hide is required.
https://github.com/metabolist/metatext/blob/0f4ec569d6575b12de5b7ba83f21eca302cc60ac/View%20Controllers/ProfileViewController.swift#L76-L80

Alternatively, when you try to add it to the list, you can ask the user "Do you want to follow?"

**Comment by jzzocc** [comment]
Thank you, this has been fixed by PR #4
