### ISSUE TITLE
Can't search for posts or users by URL

### ISSUE THREAD

**Issue by VyrCossont** [metabolist/metatext#31]
**Describe the bug**
Searching for a Mastodon user or post by URL returns no results.

**To Reproduce**
1. Open the "Discover" tab
2. Set the search type to "All"
3. Paste or type in an HTTPS URL representing a Mastodon user or post (public, unlisted, or followers-only).

**Expected behavior**
If the user or post is accessible to this user, searching should fetch and display the user or post.

**Screenshots**
n/a

**Version and device information:**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14.4.2
 - App Version: 1.0.4 (4)

**Additional context**
This is definitely a regression vs. Mastodon's web interface, Toot!, Mast, and Amaroq (at least). I'm not sure if it's a regression from previous versions of Metatext, or if it's normally implemented as a client or server feature.

Opening Mastodon URLs sent by friends through channels other than Mastodon is a major part of my workflow.

**Comment by jzzocc** [comment]
Ah yes, I need to set the search request to resolve URLs, thanks for pointing this out.

**Comment by jzzocc** [comment]
This will fixed in v1.5.0
