### ISSUE TITLE
Boost button does not work

### ISSUE THREAD

**Issue by thagorastos** [metabolist/metatext#34]
I find that most of the times I tap the Boost button, though it gives me a visual feedback that I pressed it (it slightly changes its color) does not do anything. All the other buttons work correctly. What gives?

I’m using Metatext on my iPad Pro 9,7 (lasted OS version) and my iPhone SE (latest OS version). The issue remains in the last few Metatext versions.

**Comment by jzzocc** [comment]
Do you have "Require double tap to reblog" enabled in your preferences?

**Comment by thagorastos** [comment]
Indeed I have. Please consider disabling it by default, or provide an indication when the user firstly opens and uses the app. If you've already done this, forgive me as I've forgotten.

Thank you for your time and this awesome app!
