### ISSUE TITLE
App preference for overriding font size

### ISSUE THREAD

**Issue by marrus-sh** [metabolist/metatext#37]
I’m currently running iPad Metatext on macOS [Apple Silicon] (which I realize is not properly within the scope of this project). However, everything seems to be working fine. Yet, there is no equivalent (to my knowledge) of Dynamic Type on macOS, so the font size winds up looking quite small (and it is not possible to make it bigger).

Having an in‐app slider to increase the font size within the app would be greatly appreciated!

**Comment by jzzocc** [comment]
iOS now lets you set font size per app: https://www.theverge.com/22580423/ios-15-iphone-text-size-how-to-control-center

**Comment by sammcj** [comment]
That accessibility option doesn't let you go any smaller than 80% which is still quite large.

**Comment by rcarmo** [comment]
I've reviewed both issues related to font size and tried the accessibility options and agree that this is still not enough control.
