### ISSUE TITLE
Notifications are not shown in sorted order

### ISSUE THREAD

**Issue by gabebw** [metabolist/metatext#39]
**Describe the bug**

Notifications are not sorted by date: some recent notifications are in the middle of the list, with older ones at the bottom and some medium-new ones at the top. For example (1 is the newest, 9 is the oldest timestamp):

4
5
6
1
2
3
7
8
9

**To Reproduce**
1. Go to "Notifications" tab
2. See notifications out of order

**Expected behavior**
The notifications should be listed most-recent-first.

**Screenshots**

**(please complete the following information):**
 - Device: iPhone 12 Mini
 - OS: iOS 14.6
 - App Version: 1.5.0 (4)

**Additional context**

Push notifications arrive at the correct time, but when I open Notifications, I need to search for what just happened.

**Comment by prplecake** [comment]
I just ran into this to on a new instance, but I don't think that should matter.

To get rid of them I had to reinstall the app.

**Comment by jzzocc** [comment]
Fixed in v1.5.1
