### ISSUE TITLE
Emoji in profile names renders incorrectly

### ISSUE THREAD

**Issue by mcg** [metabolist/metatext#41]
Some posts from users with emoji in their profile name render badly. Looks like a text wrap issue maybe. Attaching an image with an example of this happening. The emoji gets rendered twice and behind the text of the post.
![IMG_1589](https://user-images.githubusercontent.com/305/125476449-40fe6bcf-1b9c-4f96-9ebb-fcdcff8a5ac8.jpeg)

**Comment by CodingItWrong** [comment]
May be related to #45

**Comment by MaybeThisIsRu** [comment]
#45 has now been fixed. Does this issue still exist?

**Comment by mcg** [comment]
Fixed for me.
