### ISSUE TITLE
Additional Icon Option — Black Logo with White Background

### ISSUE THREAD

**Issue by mdrockwell** [metabolist/metatext#42]
**Is your feature request related to a problem? Please describe.**
Not a problem, necessarily, just a personal preference. I like having contrast between app icons on my iPhone home screen and having a white background option would give me a bit more freedom to place the icon next to apps with darker icons. I suspect there are others that feel the same.

**Describe the solution you'd like**
Introduce another app icon option that uses the same design as the default icon, but with a black logo and white background.

**Comment by pimoore** [comment]
Seconding Mike’s suggestion.  I’d also love to see theming options come to the app if not on the roadmap already.

**Comment by two-thirty-seven** [comment]
There is a black on white icon in the source assets but it hasn’t been wired into the code yet, by the looks.
