### ISSUE TITLE
Square Profile Picture Option

### ISSUE THREAD

**Issue by mdrockwell** [metabolist/metatext#43]
**Is your feature request related to a problem? Please describe.**
The Mastodon web interface displays profile icons as square, not round. It would be nice if there was an option to do the same within Metatext.

**Describe the solution you'd like**
Add an option in the app's Preferences screen to display profile pictures as square.

**Comment by pimoore** [comment]
To add to this would perhaps be the option to change the profile icon size, along with maybe different spacing/font settings for the feed at the same time.
