### ISSUE TITLE
Character counter showing a 500 char limit regardless of server

### ISSUE THREAD

**Issue by pitermach** [metabolist/metatext#5]
I'm on an instance (Hometown based) which has a 1000 character limit instead of the typical 500. The other clients I use respect this and display 1000 characters remaining on the composing interface. Metatext still seems to show 500. Thankfully, this issue seems to be only presentation related, you can still send a post longer than 500 characters with the counter going into the negatives.

**Comment by jzzocc** [comment]
A future version will support this through the unofficial `max_toot_chars` API 👍

**Comment by jzzocc** [comment]
This will be in v1.3.0
