### ISSUE TITLE
Compatibility with Hometown's local-only posting

### ISSUE THREAD

**Issue by MaybeThisIsRu** [metabolist/metatext#53]
**Is your feature request related to a problem? Please describe.**
Metatext makes using the Fediverse very nice on my phone. I prefer it to my [Hometown instance's](https://github.com/hometown-fork/hometown/wiki/Hometown-servers) progressive web app, to my surprise.

**Describe the solution you'd like**
It would be really cool to support its local-only posting.

**Describe alternatives you've considered**
Use two apps. Not fun.

**Additional context**
The venerable [Darius Kazemi](https://tinysubversions.com/) makes and maintains Hometown, which [has this feature](https://github.com/hometown-fork/hometown#local-only-posting).

Here's what it looks like:

![image](https://user-images.githubusercontent.com/3974019/143776949-e29556db-9226-4a51-9609-aae8b5b23209.png)

The API endpoint is the same as that of a status, with one additional parameter:

https://github.com/hometown-fork/hometown/blob/hometown-dev/app/controllers/api/v1/statuses_controller.rb#L50

**Comment by a-dows** [comment]
+1 for this request!

**Comment by bixfrankonis** [comment]
Yes, please.

**Comment by jzzocc** [comment]
Features of forks are out of scope of the app for now, unfortunately.
