### ISSUE TITLE
Icons merge with the text

### ISSUE THREAD

**Issue by Schnappa** [metabolist/metatext#54]
In some toots a blue icon with a „M“ (for Mastodon?) merges with the text (see screenshot).
![F2C9445A-6074-4AA0-84B8-C60F9D13CEAF](https://user-images.githubusercontent.com/2069599/144058074-1f92183e-14d1-4cb9-a91a-827907881660.jpeg)

**Comment by hansvurst-foss** [comment]
This issue describes the bug/ behavior of Emojis that are part of the Users Name being displayed with a vertical offset in relation to the name.

**Comment by jzzocc** [comment]
Fixed in v1.5.1
