### ISSUE TITLE
Supporting Misskey

### ISSUE THREAD

**Issue by xplosionmind** [metabolist/metatext#55]
**Is your feature request related to a problem? Please describe.**. 
No

**Describe the solution you'd like**
Making Metatext work as a client for [Misskey](https://github.com/misskey-dev/misskey), too.

**Describe alternatives you've considered**
Using one of the very few, buggy and old apps on the App Stire.

**Additional context**
\-

**Comment by S0ulf3re** [comment]
Would love to see this as well.

**Comment by jzzocc** [comment]
Out of scope for now, sorry
