### ISSUE TITLE
Accessibility: A couple of suggestions to streamline rotor actions

### ISSUE THREAD

**Issue by pitermach** [metabolist/metatext#6]
I've been loving MetaText so far and the work you've put into it. I particularly love the number of options available from the VoiceOver rotor actions. I have a couple of small suggestions to streamline the experience even more, based on behavior from other Mastodon and Twitter clients.

- Put any clickable links, usernames and hashtags as the first actions. They're currently sandwiched between a couple of options, so it takes 4 or 5 swipes from either direction to get to the first link. Having them show up first would make it easier to quickly open links from a post.
- Speaking of the links, you probably don't need the "Activate link: " phrase before each action. At least in my opinion hearing the URL or hashtag is self explanatory on its own what selecting the action would do and it also takes up less space on a braille display, it's also how the Twitterrific app does it which popularized the concept of putting links in actions like this. Alternatively the message could just be shortened to just "open" or "link" which is how a few other apps do it.
- Lastly, If the post contains any media, there could also be an action to quickly open the image in fullscreen or bring up the video/audio player, put as one of the first actions like links. This would just cut down on the number of taps you have to do to start playing a video or audio attachment, since right now you first need to go into the details screen and tap on the media again to do this which takes some flicking to find.

**Comment by jzzocc** [comment]
These are very good suggestions, thank you for taking the time to write them out. I will likely implement them in a future version.

**Comment by jzzocc** [comment]
These will be released in 1.0.2
