### ISSUE TITLE
Cannot paste

### ISSUE THREAD

**Issue by dirkhusemann** [metabolist/metatext#63]
Pasting of copied text does not work.

**Comment by prplecake** [comment]
Can you provide more info?

I copy/paste to/from Metatext all the time, including media.

**Comment by lamnatos** [comment]
I'm not seeing this either.

**Comment by dirkhusemann** [comment]
> Can you provide more info?
> 
> I copy/paste to/from Metatext all the time, including media. 

Hmm, weird. I've got text in the copy buffer and when starting a new toot and when tapping into the text field I don't get the "paste" pop-up one usually gets in iOS.

**Comment by dirkhusemann** [comment]
Ah. Never mind. Figured it out: you need to tap right in the first line.
