### ISSUE TITLE
Abandoned

### ISSUE THREAD

**Issue by prplecake** [metabolist/metatext#66]
Pretty sure this project has been abandoned by @jzzocc. They haven't pushed anything since May 2021, which appears to be the same time they stopped using Mastodon.

A damn shame, this was by far my favorite mastodon app.

Additionally their published contact email (info@metabolist.org) just bounces.

**Comment by CodingItWrong** [comment]
Minor update: https://mastodon.social/@metabolist/108227592981417610

**Comment by prplecake** [comment]
> Minor update: [mastodon.social/@metabolist/108227592981417610](https://mastodon.social/@metabolist/108227592981417610)

I saw that! I think I complained too much 😅
