### ISSUE TITLE
Faster Account Switching

### ISSUE THREAD

**Issue by conigs** [metabolist/metatext#67]
It's been pointed out that this already exists. Oops.

**Is your feature request related to a problem? Please describe.**
~~I use different accounts to follow and post about different interests. It’s a small thing, but taking three taps (profile picture, accounts, choose account) to change an account adds up.~~

**Describe the solution you'd like**
~~A long press on the profile picture on the upper left could bring up a list I could either slide down and choose, or tap. ~~

**Describe alternatives you've considered**
~~Another option would be to show the meat of accounts at the top level of the profile screen, but I’m unsure of the effects this would have on the rest of the settings~~

**Additional context**
~~I was a user of Tweetbot before leaving Twitter. They have a great account switching feature pretty similar to what I described.~~

**Comment by MaybeThisIsRu** [comment]
> Describe the solution you'd like
> A long press on the profile picture on the upper left could bring up a list I could either slide down and choose, or tap.

You can already do this. Press and hold, without leaving your touch, slide down to the other account. I use it daily.

**Comment by conigs** [comment]
I humbly withdraw my request.
