### ISSUE TITLE
Misskey Support

### ISSUE THREAD

**Issue by 4ioskd** [metabolist/metatext#70]
Hello, I'm Dignified Silence. Misskey Contributor.

Do you have a plan to make metatext work as a client app for Misskey?
Misskey is one of fediverse software which has rich features and a flexible UI.

Misskey Official Website: https://misskey-hub.net/
Misskey API Documentation on Misskey instance: https://misskey.io/api-doc

**Comment by MaybeThisIsRu** [comment]
Duplicate: #55

**Comment by 4ioskd** [comment]
Thank you, MaybeThisIsRu. I didn't notice that.
So, close this issue.
