### ISSUE TITLE
App-specific light/dark mode toggle

### ISSUE THREAD

**Issue by peterrauscher** [metabolist/metatext#73]
The app's theme is tied to system-wide light or dark setting. I prefer light theme for my social apps and dark theme for everything else, so I'd love to see an option to toggle between the two in the in-app preferences without affecting the system-wide setting. I tend to see this implemented as a drop-down list with three options: Light, Dark, or Match System.

**Comment by theotherlinh** [comment]
I know this app is more in maintenance mode, but I'd love to see this.  And maybe an additional "not quite dark mode" like the main app.

**Comment by splorp** [comment]
> I prefer light theme for my social apps and dark theme for everything else, so I'd love to see an option to toggle between the two in the in-app preferences without affecting the system-wide setting.

Even though I prefer the opposite of Peter's theme settings, a manual toggle feature would be equally useful.

**Comment by marshallmick007** [comment]
> I know this app is more in maintenance mode, but I'd love to see this. And maybe an additional "not quite dark mode" like the main app.

A not-quite-so-dark mode would be amazing. +1

**Comment by vollkorntomate** [comment]
Hi there!
I looked into this today and just opened a pull request that would allow you to set a color scheme independently from the system setting. Have a look at it, I am open to feedback!
However, I didn't do anything in the direction of a "not-quite-so-dark mode". That's something for another day :)

**Comment by peterrauscher** [comment]
> Hi there! I looked into this today and just opened a pull request that would allow you to set a color scheme independently from the system setting. Have a look at it, I am open to feedback! However, I didn't do anything in the direction of a "not-quite-so-dark mode". That's something for another day :)

I was planning on getting around to this but got very busy with school. Thanks so much for your contribution, seems like a lot of others wanted this feature too!
