### ISSUE TITLE
Data could not be read or missing

### ISSUE THREAD

**Issue by ghost** [metabolist/metatext#74]
Hello there thank you for your nice on metatext!!

I have been trying to login using metatext to my pixelfed instance 

https://freshice.org 

but I keep getting this error which says data missing or cannot be read attaching a screenshot for your reference 

any help would be highly supportive as I contacted pixelfeds main instance seems to be loading and working well.

https://pixelfed.social is working fine and I got the same number instance at freshice.org it does not load at all

![C5A89427-0DFF-409F-92B4-A1D54E22C535](https://user-images.githubusercontent.com/75223599/168425465-23270126-6a6f-4ff5-8055-0554891a150c.png)

**Comment by SathyaBhat** [comment]
I echo this, I get the same problem. At first, I thought it was maybe something wrong with my instance, but following the mastodon APIs, I get a response. For ex, this is response for public timelines from my instance

```
curl --request GET \
  --url https://pixelfed.sathyasays.com/api/v1/timelines/public \
  --header 'Authorization: Bearer <token>'
```

https://gist.github.com/SathyaBhat/294a5d47c0cf6793f144eba6f2146aa6
