### ISSUE TITLE
Open a profile in the browser

### ISSUE THREAD

**Issue by gil** [metabolist/metatext#78]
**Is your feature request related to a problem? Please describe.**

I often need to open someone’s profile on the browser to read toots that aren’t available on my instance.

**Describe the solution you'd like**

A quicker way to open the profile I’m looking at, on the fault browser 

**Describe alternatives you've considered**

Maybe a button, icon, long press the user name, or something like that.

**Additional context**

I’m sorry if this feature already exists, I tried many things but couldn’t find it. Maybe that’s not a common use case? I’m new to Mastodon.

What I’m doing now is:

1. Open profile
2. Click on the 3 dots icon
3. Share
4. Open in default browser

But that feels like a lot, if it’s actually a common use pattern. What do you folks think?

Thanks for the great app!!

**Comment by gil** [comment]
They've solved this on the web version with a link at the bottom of the profile saying something like "Previous toots from other servers are not displayed. See more on the original profile."

Screenshot in Portuguese:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/116157/200804525-ed01565f-a8c4-4315-b916-f6533ff6a494.png">

**Comment by jzzocc** [comment]
Not considering a redesign of this at this time

**Comment by gil** [comment]
Thanks @jzzocc , no worries then!

I'm curious, though. Do you have this same workflow (Sharing sheet -> Browser) when you want to see the full profile of someone from another instance? Or you don't need that often? Asking as I'm new to Mastodon, and still learning.
