### ISSUE TITLE
No notification badge on iOS

### ISSUE THREAD

**Issue by jcarnat** [metabolist/metatext#83]
**Describe the bug**
It seems the icon never gets the badge when I have a notification. I do receive the alert in the notification center etc but I never get the badge.

**To Reproduce**
Configuration is attached. My iOS is in French.

![B8A59466-E0E4-472E-B7B4-568BE239D24F](https://user-images.githubusercontent.com/1459020/186246738-298011db-a847-4ccf-b903-fd7a9e54463a.jpeg)

**Expected behavior**
Have a red dot on top of the icon when I have unread notifications.

**(please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 15.6
 - App Version 1.5.1 (2)

**Comment by snan** [comment]
I've never gotten a notification from Metatext.

My settings:

![IMG_1607](https://user-images.githubusercontent.com/309417/193429669-65c66998-36da-4cec-8076-bd689bf42faa.jpeg)

**Comment by 0xdea** [comment]
I have the same problem, confirmed on Metatext 1.5.3 on iOS 15.7.1. Notification badges don't show up regardless of settings.

**Comment by snan** [comment]
Maybe related to [this issue](https://github.com/kensanata/bitlbee-mastodon/issues/37) 🤷🏻‍♀️

**Comment by DrHyde** [comment]
> Maybe related to [this issue](https://github.com/kensanata/bitlbee-mastodon/issues/37) 🤷🏻‍♀️

I'm connected to fosstodon.org, which is Mastodon, not Pleroma

**Comment by jzzocc** [comment]
See  #51
