### ISSUE TITLE
Image description might overlap image

### ISSUE THREAD

**Issue by thegcat** [metabolist/metatext#87]
**Is your feature request related to a problem? Please describe.**

Long image descriptions might overlap the image.

https://chaos.social/@ttk/109145957396121126

**Describe the solution you'd like**

Ability to minimise/dismiss image descriptions when viewing an image.

For example: klicking the description reduces the description to maximum one line.

**Comment by prplecake** [comment]
tapping the image hides the rest of the metatext interface including the alt text.
