### ISSUE TITLE
Pictures couldn’t get loaded 

### ISSUE THREAD

**Issue by Aluhut** [metabolist/metatext#91]
**Describe the bug**
Whenever there’s a picture in a toot, there’s just a blurry preview. When I tap on it, it says “couldn’t load picture”

**To Reproduce**
As described above, every toot with a picture 

**Expected behavior**
Well, that I could see the picture. Maybe even in the toot without (trying) opening it. 

**Screenshots**

**(please complete the following information):**
 - Device: iPhone 13 Pro 
 - OS: 16.2
 - App Version 1.5.1(2)

**Additional context**

**Comment by prplecake** [comment]
This is happening for *every* image for you?

**Comment by Aluhut** [comment]
I just looked through the whole feed. Just a couple have recognizable pictures but I have no clue what's the difference between those and the others.

**Comment by prplecake** [comment]
I think Metatext shows that error when you're trying to look at a picture of a deleted post. (Metatext doesn't remove those from the timeline like the web app does, #15 #57), or if you instance can't load the image through it's proxy.

**Comment by Aluhut** [comment]
Sorry, but I doubt that. I just checked Posts where pictures are not get shown. People are commenting on it and stuff, so it indicates for me that it’s still there. Here’s is an [Example ](https://mastodon.art/@davidlopez/108243897166719755)

**Comment by prplecake** [comment]
That example works for me, so it rules out Metatext as the problem!

**Comment by Aluhut** [comment]
> Are you sure your instance isn't rejecting media from mastodon.art?

Pretty sure, there’s a lot more where’s no picture showed. And I’m extremely sure it’s not just .art

[](https://mastodon.social/@duckporn/109261865203974055) 
[](https://mastodon.art/@egonforever/109262222317237172) 
[](https://troet.cafe/@doodlebrink/109262240292019132) 

just three random posts with no viewable pictures, I hope that helps

**Comment by jzzocc** [comment]
This is most likely an issue with your instance
