### ISSUE TITLE
Error Message when returning 

### ISSUE THREAD

**Issue by cawer1990** [metabolist/metatext#94]
On iPhone 8 / iOS 15.6.1 / Version 1.5.1 (2)

When Metatext is opened and runs in the background: I get an Error Message „Zeitüberschreitung bei der Anforderung“ when i return to the App a few minutes later.

**To Reproduce**
1. Open Metatext
2. Open another App (and wait a few minutes)
3. Go back to Metatext 

**Screenshots**
![DF611682-FD52-4EE6-9C61-ABF1F363E657](https://user-images.githubusercontent.com/117161390/199206463-20dd26b6-512c-4ccc-ae78-85145d5f1ebe.png)

**Comment by prplecake** [comment]
For those that don't want to translate themselves, this is a "Request timeout" error

**Comment by audioflyer** [comment]
I have the same issue.

**Comment by jzzocc** [comment]
This is due to a request to your instance timing out
