### ISSUE TITLE
CW shows link preview

### ISSUE THREAD

**Issue by yuki-93** [metabolist/metatext#95]
**Describe the bug**
If you tag a toot with a content warning, it shows a link preview. 
I thing / would recommend to hide this also. 

Use-case: there was a toot I like to share, but with a CW. So I simply put the link in a toot. But this gets also a preview. I would expect to have this information also hidden behind the "show CW content" spoiler.

**Comment by ThisIsMissEm** [comment]
Here's a screenshot 
![E15AF7D5-AABD-4F6D-A99D-957657D17683](https://user-images.githubusercontent.com/30827/200349299-1f2b7aac-ce7b-470a-a1d3-4cbb4c92aa3d.jpeg)

**Comment by prplecake** [comment]
Media aren't hidden behind the click-through "show more" button either, but at least they're hidden behind the sensitive media blur.

**Comment by jzzocc** [comment]
See  #58
