### ISSUE TITLE
param is missing or the value is empty: q Did you mean? a action controller resolve

### ISSUE THREAD

**Issue by x-industries-uk** [metabolist/metatext#96]
**Describe the bug**
When using the search page, an alert keeps appearing, which reads:

> param is missing or the value 
> is empty: q
> Did you mean? a
> action controller resolve

**To Reproduce**
1. Go to the search page
2. If the alert doesn't appear, tap on the searchbar.
3. See error

**Expected behavior**
The alert does not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/67475141/200027067-f6c15f36-0962-4c39-af7d-0ee7633e607a.png)

**Device Info:**
 - Device: iPhone SE (2nd Generation)
 - OS: iOS 16.1 (20B82)
 - App Version 1.5.1 (2)

**Additional context**
I am using [mastodon.social](https://mastodon.social/).

**Comment by DerZyklop** [comment]
To me this happens always when I type something in the search input and remove it again. Removing the last remaining letter triggers this error.
